### ISSUE TITLE
哈哈哈哈  python 按键精灵

### ISSUE THREAD

**Issue by 331319341** [yangyuan/rabbit#2]
一个问题 ，现在 pyhook   挂不住 游戏里面的钩子，表现在 进入  LOL 或者 DNF等游戏 后获取不到，键盘的输入  。不知道  rabbit  能获取到吗 ？ 感谢

**Comment by yangyuan** [comment]
rabbit 只能模拟输入，不能作为 hook，所以做不了。

pyhook 应该只是 hook 住了 SentInput 函数，D3D 游戏里一般用的是 DX 的输入函数，比较底层，所以获取不到。
