### ISSUE TITLE
How to start the app?

### ISSUE THREAD

**Issue by daokunjiang** [yangyuan/rabbit#3]
I have installed rabbit-bot package through pip install and written a script.py.
Where should I put the script.py file and how to start that?
Thanks~

**Comment by yangyuan** [comment]
You can either
- Run the python script directly.
- Download the latest release (support win10), put script.py in the same folder as rabbit.exe. Run rabbit.exe. F7 to start, F8 to terminate.

If you use an older version of windows you can compile the project by yourself.
If you use rabbit.exe, you don't have to install either pip package or npm package. You dont even have to install python and node.js

**Comment by daokunjiang** [comment]
Thanks.
It works well 👍
